### ISSUE TITLE
Module Registry Page Updates

### ISSUE THREAD

**Issue by spacelift-ryan** [spacelift-io/user-documentation#235]
On the module registry, https://docs.spacelift.io/vendors/terraform/module-registry, can we add details on dependecy for public workers vs private workers? Are both supported?

I know there is a dependency for workers, but our documentation doesn’t define the dependency.

Is there a diagram on the moving pieces of our module registry?

**Comment by jmfontaine** [comment]
Closing as these requests are being tracked internally.
