### ISSUE TITLE
Add Error Message for Free Trial expiration

### ISSUE THREAD

**Issue by spacelift-ryan** [spacelift-io/user-documentation#236]
Add error message details and screenshot for when trial expires to FAQ page. https://docs.spacelift.io/faq/

![IMG_2855](https://github.com/spacelift-io/user-documentation/assets/135669307/f90742e7-07a9-4f24-b614-4bff0e8ecd53)

**Comment by jmfontaine** [comment]
Unfortunately, those errors could be unrelated to an expired trial. There is a feature request in our backlog to explicitly mention that some actions failed due to an expired trial so I am closing this request.
